name: BuildTest
on: [push, pull_request]

jobs:
  build_test:
    name: Build & Test
    runs-on: ubuntu-latest
    if: github.event.inputs.version == ''
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build
        run: dotnet build PixelGraph.Tests -c Test
      - name: Test
        run: dotnet test PixelGraph.Tests -c Test
