name: Build, Test, Publish
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version number.'
        required: false

jobs:
  build_test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          dotnet restore
          dotnet build
      - name: Test
        run: dotnet test
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build_test
    if: github.event.inputs.version != ''
    steps:
      - uses: actions/checkout@v2
      - name: Publish Windows x64
        run: dotnet publish -c Release -r win-x64 -o ./publish/win-x64 -p:PublishSingleFile=true --no-self-contained
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          draft: true
      - name: Upload Windows x64 Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./publish/win-x64/MCPBRP.exe
          asset_name: MCPBRP-win-x64.exe
          asset_content_type: application/exe
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish Dockerfile
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/386,linux/amd64
          push: true
          tags: |
            null511/mcpbrp:latest
            null511/mcpbrp:${{ github.event.inputs.version }}
