name: Manual triggered publishing workflow
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version number.'
        required: false

jobs:
  build:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: dotnet restore
      - run: dotnet build
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test Release
        run: dotnet test
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: test
    if: github.event.inputs.version != ''
    steps:
      - name: Publish Windows x64
        run: dotnet publish -c Release -r win-x64 -o /publish/win-x64 -p:PublishSingleFile=true --no-self-contained
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          draft: true
      - name: Upload Windows x64 Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /publish/win-x64/MCPBRP.exe
          asset_name: MCPBRP-win-x64.exe
          asset_content_type: application/exe
