name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version number.'
        required: true

jobs:
  publish-cli:
    name: Publish-CLI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish CLI Binaries
        run: |
          cd PixelGraph.CLI
          dotnet publish -c Release -r win-x64 -o ../publish/win-cli-x64 -p:PublishSingleFile=true --self-contained false
          dotnet publish -c Release -r linux-x64 -o ../publish/linux-cli-x64 -p:PublishSingleFile=true --self-contained false
          dotnet publish -c Release -r osx-x64 -o ../publish/osx-cli-x64 -p:PublishSingleFile=true --self-contained false
      - name: Upload Windows-CLI-x64 Binary
        uses: actions/upload-artifact@v2
        with:
          name: Windows-CLI-x64
          path: publish/win-cli-x64/PixelGraph.exe
      - name: Upload Linux-CLI-x64 Binary
        uses: actions/upload-artifact@v2
        with:
          name: Linux-CLI-x64
          path: publish/linux-cli-x64/PixelGraph
      - name: Upload OSX-CLI-x64 Binary
        uses: actions/upload-artifact@v2
        with:
          name: OSX-CLI-x64
          path: publish/osx-cli-x64/PixelGraph
  publish-ui:
    name: Publish-UI
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Windows-UI-x64 Binary
        run: |
          cd PixelGraph.UI
          dotnet publish -c Release -r win-x64 -o ../publish/win-ui-x64 -p:PublishSingleFile=true --self-contained false
      - name: Upload Windows-UI-x64 Binary
        uses: actions/upload-artifact@v2
        with:
          name: Windows-UI-x64
          path: publish/win-ui-x64/PixelGraph.exe
  publish-release:
    name: Publish-Release
    runs-on: ubuntu-latest
    needs: [publish-cli, publish-ui]
    steps:
      - uses: actions/checkout@v2
      - name: Download Windows-CLI-x64 Binary
        uses: actions/download-artifact@v2
        with:
          name: Windows-CLI-x64
          path: win-cli-x64/PixelGraph.exe
      - name: Download Linux-CLI-x64 Binary
        uses: actions/download-artifact@v2
        with:
          name: Linux-CLI-x64
          path: linux-cli-x64/PixelGraph
      - name: Download OSX-CLI-x64 Binary
        uses: actions/download-artifact@v2
        with:
          name: OSX-CLI-x64
          path: osx-cli-x64/PixelGraph
      - name: Download Windows-UI-x64 Binary
        uses: actions/download-artifact@v2
        with:
          name: Windows-UI-x64
          path: win-ui-x64/PixelGraph.exe
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          draft: true
      - name: Release Windows-CLI-x64 Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./win-cli-x64/PixelGraph.exe
          asset_name: PixelGraph-CLI-win-x64.exe
          asset_content_type: application/exe
      - name: Release Linux-CLI-x64 Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./linux-cli-x64/PixelGraph
          asset_name: PixelGraph-CLI-linux-x64
          asset_content_type: application/exe
      - name: Release OSX-CLI-x64 Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./osx-cli-x64/PixelGraph
          asset_name: PixelGraph-CLI-osx-x64
          asset_content_type: application/exe
      - name: Release Windows-UI-x64 Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./win-ui-x64/PixelGraph.exe
          asset_name: PixelGraph-UI-win-x64.exe
          asset_content_type: application/exe
      - name: Publish Dockerfile
        uses: docker/build-push-action@v1
        with:
          repository: null511/pixelgraph
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          tags: latest,${{ github.event.inputs.version }}
